set(CMAKE_C_FLAGS "/fsanitize=address ${CMAKE_C_FLAGS}")
set(CMAKE_CXX_FLAGS "/fsanitize=address ${CMAKE_CXX_FLAGS}")

set(CMAKE_EXE_LINKER_FLAGS "/INCREMENTAL:NO /DEBUG /stack:10000000")
set(CMAKE_SHARED_LINKER_FLAGS "/INCREMENTAL:NO /DEBUG")

set(USE_MIMALLOC OFF)
set(SANITISE ON)
