function(enable_sanitisers target)
     if (SANITISE MATCHES "address")
          if (MSVC)
               target_compile_options(${target} PRIVATE /fsanitize=address)
               target_link_options(${target} PRIVATE /fsanitize=address)
          elseif (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
               target_compile_options(${target} PRIVATE -fsanitize=address)
               target_link_options(${target} PRIVATE -fsanitize=address)
          endif()
     endif()

     if (SANITISE MATCHES "undefined")
          if (MSVC)
               # not supported yet
          elseif (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
               target_compile_options(${target} PRIVATE -fsanitize=undefined)
               target_link_options(${target} PRIVATE -fsanitize=undefined)
          endif()
     endif()

     if (SANITISE MATCHES "thread")
          if (MSVC)
               # not supported yet
          elseif (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
               target_compile_options(${target} PRIVATE -fsanitize=thread)
               target_link_options(${target} PRIVATE -fsanitize=thread)
          endif()
     endif()
endfunction()
