name: CI — Development

on:
  push:
    branches: [development]

concurrency:
  group: ci-development
  cancel-in-progress: true

jobs:
  define-build-matrix:
    runs-on: ubuntu-latest
    outputs:
      windows-matrix: ${{ steps.set-matrix.outputs.windows-matrix }}
      linux-matrix: ${{ steps.set-matrix.outputs.linux-matrix }}
    steps:
      - id: set-matrix
        run: |
          cat << 'EOF' >> $GITHUB_OUTPUT
          windows-matrix=[{"compiler":"Clang","name":"clang20","build_type":"Release","preset_configure":"Win64-Clang-Release","preset_build":"Win64-Clang-Release-Build","needs_msvc":false,"needs_llvm":true}]
          linux-matrix=[{"compiler":"Clang","name":"clang20","build_type":"Release","preset_configure":"Linux-Clang-Release","preset_build":"Linux-Clang-Release-Build","needs_llvm":true}]
          EOF

  clang-format:
    uses: ./.github/workflows/_clang-format.yml

  build-windows:
    needs: [define-build-matrix, clang-format]
    uses: ./.github/workflows/_build.yml
    with:
      os: windows-latest
      matrix-config: ${{ needs.define-build-matrix.outputs.windows-matrix }}
      upload-artifacts: true
      enable-lto: true

  build-linux:
    needs: [define-build-matrix, clang-format]
    uses: ./.github/workflows/_build.yml
    with:
      os: ubuntu-latest
      llvm-version: "20"
      matrix-config: ${{ needs.define-build-matrix.outputs.linux-matrix }}
      upload-artifacts: true
      enable-lto: true

  tests:
    needs: [build-windows, clang-format]
    uses: ./.github/workflows/_tests.yml

  clang-tidy:
    needs: [build-windows, build-linux]
    uses: ./.github/workflows/_clang-tidy.yml

  sanitisers:
    needs: [build-windows, build-linux]
    uses: ./.github/workflows/_sanitisers.yml
